---
engines:
  csslint:
    enabled: true
    checks:
      adjoining-classes:
        enabled: false
      order-alphabetical:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  tslint:
    enabled: true
    checks:
      quotemark:
        enabled: false
    channel: beta
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- config/
- dist/
- test/
- public/
