language: node_js
node_js:
  - "6"
notifications:
  slack: 
    rooms: circlemapping:Y7RTefJI5CznwbeFqMeqvnno
    on_pull_requests: false
addons:
    code_climate:
        repo_token: 0d513f44c10e35dacbc815a38ded75a76f286f29a40f0b5597b4cd62a1bf8a10
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov/lcov.info